### ISSUE TITLE
HitBTC wss error

### ISSUE THREAD

**Issue by CarlitoGrey** [michaelgrosner/tribeca#150]
Hey,

I have tribeca running on Coinbase however on HitBTC I am seeing the below error:

msg":"socket error { Error: connect ECONNREFUSED 67.207.73.210:8080\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)\n  code: 'ECONNREFUSED',\n  errno: 'ECONNREFUSED',\n  syscall: 'connect',\n  address: '67.207.73.210',\n  port: 8080 }","time":"2017-07-14T14:53:43.161Z","v":0}
{"name":"ws:wss://api.hitbtc.com:8080","hostname":"Krypto-Netherlands","pid":33562,"level":30,"msg":"will try a reconnect in 5000ms, failed 8 times","time":"2017-07-14T14:53:43.161Z","v":0}

Any help would be appreciated!

**Comment by michaelgrosner** [comment]
I am seeing the same thing too. I think they might be having system issues. I'll email them.

**Comment by CarlitoGrey** [comment]
Michael, it seems there may have been some changes on their part? Please see https://github.com/ctubio/Krypto-trading-bot/commit/2cdeaaeded05088d36b01c7388f934d9004e33e4
https://github.com/ctubio/Krypto-trading-bot/commit/1a28b5bb331461feae66248abce417b154fdbcf8

**Comment by CarlitoGrey** [comment]
I'd also be happy to pass on some donation to support HitBTC on tribeca.

**Comment by michaelgrosner** [comment]
They still haven't gotten back to my initial support request. Is it working for anyone now?

**Comment by CarlitoGrey** [comment]
Michael,

I have stepped through this as much as I can, I see that there is data in the raw object, however raw.data is null on occasion. I've tried to fix it but it's beyond me at the moment (I was .Net guy in my dev days!).

https://github.com/michaelgrosner/tribeca/blob/18c6c0f10346c5adf4e35c9d7e432d305b320f5f/src/service/gateways/hitbtc.ts#L210

**Comment by hnykda** [comment]
Today, still the same issue.
