### ISSUE TITLE
Missing node-gyp in manual install instructions

### ISSUE THREAD

**Issue by CarlitoGrey** [michaelgrosner/tribeca#157]
I had to install this separately, should the manual install instructions be updated?

**Comment by trisztan** [comment]
Runs on the latest node.js (v7.8 or greater).

**Comment by michaelgrosner** [comment]
Can you reproduce it? Maybe I'm missing something in the basic install instructions?

**Comment by thekenshow** [comment]
I ran into node-gyp issues during a manual tribeca install as well. Trying to install it manually did not work either. After this point: 

```
cd tribeca
npm install

```
The log generated was:

```
    npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
    npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
    
    > v8-profiler@5.7.0 preinstall /var/www/tribeca/node_modules/v8-profiler
    > node -e 'process.exit(0)'
    
    
    > v8-debug@1.0.1 preinstall /var/www/tribeca/node_modules/v8-debug
    > node -e 'process.exit(0)'
    
    
    > dtrace-provider@0.8.1 install /var/www/tribeca/node_modules/dtrace-provider
    > node scripts/install.js
    
    
    > v8-debug@1.0.1 install /var/www/tribeca/node_modules/v8-debug
    > node-pre-gyp install --fallback-to-build
    
    node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-linux-x64.tar.gz 
    node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.2.1 (node-v57 ABI) (falling back to source compile with node-gyp) 
    gyp info it worked if it ends with ok
    gyp verb cli [ '/usr/local/bin/node',
    gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
    gyp verb cli   'clean' ]
    gyp info using node-gyp@3.4.0
    gyp info using node@8.2.1 | linux | x64
    gyp verb command clean []
    gyp verb clean removing "build" directory
    gyp info ok 
    gyp info it worked if it ends with ok
    gyp verb cli [ '/usr/local/bin/node',
    gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
    gyp verb cli   'configure',
    gyp verb cli   '--fallback-to-build',
    gyp verb cli   '--module=/var/www/tribeca/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64/debug.node',
    gyp verb cli   '--module_name=debug',
    gyp verb cli   '--module_path=/var/www/tribeca/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64' ]
    gyp info using node-gyp@3.4.0
    gyp info using node@8.2.1 | linux | x64
    gyp verb command configure []
    gyp verb check python checking for Python executable "python2" in the PATH
    gyp verb `which` failed Error: not found: python2
    gyp verb `which` failed     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
    gyp verb `which` failed     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
    gyp verb `which` failed     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
    gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:135:15)
    gyp verb `which` failed  python2 { Error: not found: python2
    gyp verb `which` failed     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
    gyp verb `which` failed     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
    gyp verb `which` failed     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
    gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:135:15) code: 'ENOENT' }
    gyp verb check python checking for Python executable "python" in the PATH
    gyp verb `which` failed Error: not found: python
    gyp verb `which` failed     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
    gyp verb `which` failed     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
    gyp verb `which` failed     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
    gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:135:15)
    gyp verb `which` failed  python { Error: not found: python
    gyp verb `which` failed     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
    gyp verb `which` failed     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
    gyp verb `which` failed     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
    gyp verb `which` failed     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
    gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:135:15) code: 'ENOENT' }
    gyp ERR! configure error 
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
    gyp ERR! stack     at failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:449:14)
    gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:11
    gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:16)
    gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
    gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
    gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
    gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
    gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:135:15)
    gyp ERR! System Linux 4.4.0-79-generic
    gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/var/www/tribeca/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64/debug.node" "--module_name=debug" "--module_path=/var/www/tribeca/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64"
    gyp ERR! cwd /var/www/tribeca/node_modules/v8-debug
    gyp ERR! node -v v8.2.1
    gyp ERR! node-gyp -v v3.4.0
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/tribeca/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64/debug.node --module_name=debug --module_path=/var/www/tribeca/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/tribeca/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:921:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Linux 4.4.0-79-generic
    node-pre-gyp ERR! command "/usr/local/bin/node" "/var/www/tribeca/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /var/www/tribeca/node_modules/v8-debug
    node-pre-gyp ERR! node -v v8.2.1
    node-pre-gyp ERR! node-pre-gyp -v v0.6.34
    node-pre-gyp ERR! not ok 
    Failed to execute '/usr/local/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/tribeca/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64/debug.node --module_name=debug --module_path=/var/www/tribeca/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64' (1)
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the v8-debug@1.0.1 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

After the manual node-gyp threw errors, I installed python, make, and g++ but still couldn't clear the errors.

**Comment by astrolope** [comment]
+1 on this, i'm running the latest version of node.

**Comment by ragingnerd** [comment]
Hey guys found the root cause, [node-inspector does not work on v8.x](https://github.com/node-inspector/node-inspector/issues/1013). The only workaround atm is to downgrade to v7.x
