### ISSUE TITLE
HitBtc connection issue

### ISSUE THREAD

**Issue by Morzilla** [michaelgrosner/tribeca#165]
Hello! This is my first attempt to run Tribeca on HitBtc trading site, but I have the following problem:

{"name":"tribeca:main","hostname":"1234567.kimsufi.com","pid":19913,"level":50,"err":{"message":"Unexpected token < in JSON at position 0","name":"SyntaxError","stack":"SyntaxError: Unexpected token < in JSON at position 0\n    at Object.parse (native)\n    at Request.e [as _callback] (/usr/local/share/tribeca/tribeca/service/utils.js:110:34)\n    at Request.self.callback (/usr/local/share/tribeca/node_modules/request/request.js:188:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/usr/local/share/tribeca/node_modules/request/request.js:1171:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/usr/local/share/tribeca/node_modules/request/request.js:1091:12)\n    at IncomingMessage.g (events.js:292:16)"},"msg":"Unhandled promise rejection! Promise {\n  <rejected> SyntaxError: Unexpected token < in JSON at position 0\n    at Object.parse (native)\n    at Request.e [as _callback] (/usr/local/share/tribeca/tribeca/service/utils.js:110:34)\n    at Request.self.callback (/usr/local/share/tribeca/node_modules/request/request.js:188:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/usr/local/share/tribeca/node_modules/request/request.js:1171:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/usr/local/share/tribeca/node_modules/request/request.js:1091:12)\n    at IncomingMessage.g (events.js:292:16) }","time":"2017-09-04T21:38:10.352Z","v":0}

It seems that the script try to parse an incorrect response (maybe an HTML page that start with < tag?)  as a JSON data...I put in configuration file the correct API key and secret with the right permissions on HitBTC...how can I do to resolve or debug this issue?

Thanks everybody!

**Comment by michaelgrosner** [comment]
Sometimes this happens when the exchange is down or experiencing issues. Is it working now?
