### ISSUE TITLE
Error Socket Hangup

### ISSUE THREAD

**Issue by ScottBouloutian** [michaelgrosner/tribeca#179]
I am running tribeca in a docker container on AWS Lightsail. I am using GDAX sandbox environment and am able to connect to the client app successfully. It is able to connect and appears to be working for around 5 minutes before I get the following error:

```
{"name":"tribeca:main","hostname":"5687fc7dac36","pid":64,"level":50,"err":{"message":"soc
ket hang up","name":"Error","stack":"Error: socket hang up\n    at createHangUpError (_htt
p_client.js:302:15)\n    at TLSSocket.socketOnEnd (_http_client.js:394:23)\n    at emitNon
e (events.js:91:20)\n    at TLSSocket.emit (events.js:188:7)\n    at endReadableNT (_strea
m_readable.js:975:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\
n    at process._tickCallback (internal/process/next_tick.js:104:9)","code":"ECONNRESET"},
"msg":"Unhandled exception!","time":"2017-10-23T17:00:00.392Z","v":0}
```

Restarting docker fixes it, but the error recurs after another 5 minutes or so. I am going to try looking into this issue but I am documenting it here in case anyone else is having a similar problem or knows the solution.

**Comment by aschenoni** [comment]
I'm running into this same issue running locally. Anyone find a solution?
