### ISSUE TITLE
Error when I launch tribeca

### ISSUE THREAD

**Issue by Pascal66** [michaelgrosner/tribeca#22]
C:\tribeca\node_modules\agentkeepalive\lib\agent.js:22
var debug = util.debuglog('http');
                 ^
TypeError: Object #<Object> has no method 'debuglog'
    at Object.<anonymous> (C:\Users\Pascal\Desktop\tribeca2\node_modules\agentke
epalive\lib\agent.js:22:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Pascal\Desktop\tribeca2\node_modules\agentke
epalive\index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
error: Forever detected script exited with code: 8

**Comment by michaelgrosner** [comment]
Which version of node are you running? Run `node -v`. You need v0.12 or greater.

**Comment by Pascal66** [comment]
was 0.10 ~) Sorry Michael, 'ill try with the new version
