### ISSUE TITLE
[Error: ETIMEDOUT] code: 'ETIMEDOUT'

### ISSUE THREAD

**Issue by Mikadily** [michaelgrosner/tribeca#30]
My bot on bitfinex crashes once in a while, at random intervals. 'Forever' will restart it, but it leaves old orders hanging and it's not active - I need to click the red button (is there an autostart function?).

Crash log:
```
info: 9/3/15 05:53:49,503       [tribeca:gateway:BitfinexHTTP]  Error returned: url= https://api.bitfinex.com/v1/book/btcusd err= { 
[Error: ETIMEDOUT] code: 'ETIMEDOUT', connect: false }
error: Terminating! uncaughtException { [Error: ETIMEDOUT] code: 'ETIMEDOUT', connect: false } Error: ETIMEDOUT
    at null._onTimeout (/tribeca/node_modules/request/request.js:818:15)
    at Timer.listOnTimeout (timers.js:119:15)
Terminating! uncaughtException { [Error: ETIMEDOUT] code: 'ETIMEDOUT', connect: false } Error: ETIMEDOUT
    at null._onTimeout (/tribeca/node_modules/request/request.js:818:15)
    at Timer.listOnTimeout (timers.js:119:15)
error: Terminating! exit 1
Terminating! exit 1
error: Forever detected script exited with code: 1
error: Script restart attempt #348
```

Anything could be done about it?

**Comment by michaelgrosner** [comment]
This is a genuine timeout coming from Bitfinex. Sometimes their request/responses take > 5 seconds, which is insanely bad. I can up the timeout/make it configurable. Even when it's 15 seconds, I've had timeouts.

Humans trading on the NYSE floor can trade faster than Bitfinex. They're terrible from a tech standpoint.

**Comment by Mikadily** [comment]
Fair enough. Longer timeout doesn't seem good enough, connection drop can happen for many reasons.  Would be better to handle it in graceful manner - clean orders, start again etc.

**Comment by flufy3d** [comment]
I have the same problem ,crash once in a while
